a: float; b: float; c: float; d: float; x1: float; x2: float
print('CALCULADORA DE EQUAÇÕES DO SEGUNDO GRAU')
a = float(input('VALOR DE A: '))
b = float(input('VALOR DE B: '))
c = float(input('VALOR DE C: '))
d = b ** 2 - (4 * a * c)

if d < 0:
    print(F'DELTA NEGATIVO = {d:.0f}, RAÍZES INEXISTENTES')
    exit()

rd = d ** (1 / 2)
x1 = (-b + rd) / (2 * a)
x2 = (-b - rd) / (2 * a)
rd2 = rd ** 2
rd3 = rd2 % rd

if rd3 != 0:
    print('RESOLUÇÃO:')
    print('DELTA = b^2 - (4 x a x c)')
    print(f'DELTA = ({b})^2 - (4 x ({a}) x ({c}))')
    print(f'DELTA = ({b})^2 - (4 x ', end='')
    print(a * c, ')')
    print(f'DELTA = ', end='')
    print(b ** 2, end='')
    print(f' - (4 x ', end='')
    print(a * c, ')')
    print(f'DELTA = ', end='')
    print(b ** 2, end='')
    print(f' - (', end='')
    print(4 * a * c, ')')
    print(f'DELTA = {d}')
    print(f'X1 = -b + √Delta / 2 x a')
    print(f'X1 = -({b}) + √{d} / 2 x ({a})')
    print(f'X1 = -({b}) + √{d} /', end='')
    print(2 * a)
    print(f'X2 = -({b}) - √{d} / 2 x ({a})')
    print(f'X2 = -({b}) - √{d} /', end='')
    print(2 * a)
    exit()

print('RESOLUÇÃO:')
print(f'DELTA = {d}')
print(f'X1 = {x1}')
print(f'X2 = {x2}')
print('RESOLUÇÃO:')
print('DELTA = b^2 - (4 x a x c)')
print(f'DELTA = {b}^2 - (4 x ({a}) x ({c}))')
print(f'DELTA = {b}^2 - (4 x ', end='')
print(a * c, ')')
print(f'DELTA = ', end='')
print(b ** 2, end='')
print(f' - (4 x ', end='')
print(a * c, ')')
print(f'DELTA = ', end='')
print(b ** 2, end='')
print(f' - (', end='')
print(4 * a * c, ')')
print(f'DELTA = {d}')
print(f'X1 = -b + √Delta / 2 x a')
print(f'X1 = -({b}) + {rd} / 2 x ({a})')
print(f'X1 = -({b}) + {rd} ', end='')
print(f'/', 2 * a)
print(f'X1 = ', end='')
print(-b + rd, end='')
print(f'/', 2 * a)
print(f'X1 = {x1}')
print(f'X2 = -b - √Delta / 2 x a')
print(f'X2 = -({b}) - {rd} / 2 x ({a})')
print(f'X2 = -({b}) - {rd} ', end='')
print(f'/', 2 * a)
print(f'X2 = ', end='')
print(-b - rd, end='')
print(f'/', 2 * a)
print(f'X2 = {x2}')
